### ISSUE TITLE
Add an example of adding custom rules using eslint-parser-json

### ISSUE THREAD

**Issue by 0xdevalias** [zeitport/eslint-plugin-json#1]
It would be cool to have a basic example of how to use this to create custom rules.

Refs:

- https://eslint.org/docs/developer-guide/working-with-custom-parsers
- https://eslint.org/docs/user-guide/configuring#specifying-parser
- https://eslint.org/docs/user-guide/configuring#specifying-processor
- https://eslint.org/docs/developer-guide/contributing/new-rules#alternative-creating-your-own-rules
- https://eslint.org/docs/developer-guide/working-with-rules#rule-basics
- https://eslint.org/docs/developer-guide/working-with-plugins

**Comment by cschuller** [comment]
Thanks for your feedback.

A basic example on how to use the parser is provided in the example "branch" 
https://github.com/zeitport/eslint-parser-json/tree/example

I agree, another example that includes a custom rule would be very helpful.

**Comment by 0xdevalias** [comment]
Thanks, I did see that, but as it was using an existing rule it wasn't as helpful as I was hoping. Do you think you'd be able to add a custom-rule example? (or give me some pointers as to how to do it here?)

**Comment by cschuller** [comment]
I will add two new examples:
- with custom rule 
- with custom rule and auto-fixer.

Will be available tomorrow.

If you are familiar with custom ESLint rules and the parser you can try:
https://astexplorer.net/#/gist/006da4d4da90e46469df37a78596f11a/057ea1a4eb374bb46468eb04237d946a798fe762

This lib is just wrapping a JSON input into an ExpressionStatement. Your custom rule can start with "ObjectExpression" (Or ArrayExpression) as the entry point.

**Comment by 0xdevalias** [comment]
Amazing, thanks!

I'm not deeply familiar, but that doesn't mean I can't learn! Shall have a play and see what I come up with in the meantime :)

**Comment by cschuller** [comment]
@0xdevalias I have updated the example branch and added a full example for creating a custom ESLint rule to check the JSON.
https://github.com/zeitport/eslint-parser-json/tree/example/custom-json-rule/

Please let me know if this helpful for you.
