### ISSUE TITLE
Document how to use rule configurations

### ISSUE THREAD

**Issue by edg2s** [zeitport/eslint-plugin-json#2]
I can't see how to use the rule configurations as shared configs?

Thanks,

**Comment by cschuller** [comment]
This is a really good question and with the current package name it does not work with the ESLint fixed naming schema. 

The new flexible ESLint config engine will come in months.

It looks like that I have to rename the package from "@zeitport/eslint-parser-json" to "@zeitport/eslint-plugin-json"

But this needs some more tests.

I hope this lib is still useful for you.

**Comment by cschuller** [comment]
- package was renamed to @zeitport/eslint-plugin-json
- Documentation to use recommended settings was added to the examples at 

https://github.com/zeitport/eslint-plugin-json/tree/example/get-started#recommended-rules
